%hidden MODULE_NAME="ctp_worktrunk"

set -gq "@catppuccin_${MODULE_NAME}_icon" '🌿 '
set -gqF "@catppuccin_${MODULE_NAME}_color" '#{E:@thm_green}'
set -gq "@catppuccin_${MODULE_NAME}_text" ' #(cd "#{pane_current_path}" 2>/dev/null && wt list --format=json 2>/dev/null | jq "length" 2>/dev/null)'

source -F '#{TMUX_PLUGIN_MANAGER_PATH}/tmux/utils/status_module.conf'
